Fix indentation for POD_IP valueFrom field
fix example
- manifests/deployment.yaml

which is erroring with:
```
kubectl apply -f https://raw.githubusercontent.com/llm-d/llm-d-inference-sim/main/manifests/deployment.yaml
error: error parsing https://raw.githubusercontent.com/llm-d/llm-d-inference-sim/main/manifests/deployment.yaml: error converting YAML to JSON: yaml: line 39: did not find expected '-' indicator
```

Signed-off-by: Matteo Mortari <matteo.mortari@gmail.com>